	PROGRAM NORMA_MATRICI
* Calcolo delle norme matriciali
	USE MSIMSL
	PARAMETER(N_MAX=100)
	REAL A(N_MAX,N_MAX)
	REAL RIS,NORMA_1,NORMA_2,NORMA_INF,NORMA_FROBENIUS
	WRITE(*,*)'Inserisci l''ordine della matrice A:'
	READ(*,*)N
	CALL INIT_MATRIX(A,N_MAX,N)
	RIS=NORMA_1(A,N_MAX,N)
	WRITE(*,*)'La norma 1 e'':',RIS
	RIS=NORMA_2(A,N_MAX,N)
	WRITE(*,*)'La norma 2 e'':',RIS
	RIS=NORMA_INF(A,N_MAX,N)
	WRITE(*,*)'La norma inf e'':',RIS
	RIS=NORMA_FROBENIUS(A,N_MAX,N)
	WRITE(*,*)'La norma Frobenius e'':',RIS
	END

	SUBROUTINE INIT_MATRIX(A,N_MAX,N)
	REAL A(N_MAX,N)
	WRITE(*,*)'Inserisci i valori della matrice:'
	DO I=1,N
		READ(*,*)(A(I,J),J=1,N)
	END DO
	END

	REAL FUNCTION NORMA_1(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL SOMMA
	NORMA_1=0
	DO J=1,N
		SOMMA=0
  	DO I=1,N
			SOMMA=SOMMA+ABS(A(I,J))
		END DO
		IF(NORMA_1.LT.SOMMA)NORMA_1=SOMMA
	END DO
	END

	REAL FUNCTION NORMA_2(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL A2(N,N)
	COMPLEX EVAL(N)
	CALL MATRIX_MUL_T(A,A2,N_MAX,N,N)
	CALL EVLRG(N,A2,N,EVAL)
	NORMA_2=SQRT(ABS(EVAL(1)))
	END

	SUBROUTINE MATRIX_MUL_T(A,C,NMAX_A,NMAX_C,N)
	REAL A(NMAX_A,N),C(NMAX_C,N),SOMMA
	INTEGER I,J,K
	DO I=1,N
		DO J=1,N
			SOMMA=0
			DO K=1,N
				SOMMA=SOMMA+A(I,K)*A(J,K)
			END DO
			C(I,J)=SOMMA
		END DO
	END DO
	END

	REAL FUNCTION NORMA_INF(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL SOMMA
	NORMA_INF=0
	DO I=1,N
		SOMMA=0
		DO J=1,N
			SOMMA=SOMMA+ABS(A(I,J))
		END DO
		IF(NORMA_INF.LE.SOMMA) NORMA_INF=SOMMA
	END DO
	END


	REAL FUNCTION NORMA_FROBENIUS(A,N_MAX,N)
	REAL A(N_MAX,N)
	NORMA_FROBENIUS=0
	DO I=1,N
		DO J=1,N
			NORMA_FROBENIUS=NORMA_FROBENIUS+(A(I,J)*A(I,J))
		END DO
	END DO
	NORMA_FROBENIUS=SQRT(NORMA_FROBENIUS)
	END
