	REAL FUNCTION COND(A,NMAX,N)
	USE MSIMSL
	REAL A(NMAX,N),AINV(N,N)
	REAL NORMA,NORMAINV,NORMA_INF
	CALL LINRG(N,A,NMAX,AINV,N)
	NORMA=NORMA_INF(A,NMAX,N)
	NORMAINV=NORMA_INF(AINV,N,N)
	COND=NORMA*NORMAINV
	END
