	REAL FUNCTION NORMA_2(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL A2(N_MAX,N)
	COMPLEX EVAL(N_MAX)
	CALL MUL_A_PER_TRASPOSTA(A,A,A2,N_MAX,N)
	CALL EVLRG(N,A2,N_MAX,EVAL)			   
	NORMA_2=SQRT(ABS(EVAL(1)))
	END

	SUBROUTINE MUL_A_PER_TRASPOSTA(A,B,C,N_MAX,N)
	REAL A(N_MAX,N),B(N_MAX,N),C(N_MAX,N)
	INTEGER I,J,K
	DO I=1,N
		DO J=1, N
			C(I,J) = 0
				DO K=1,N
					C(I,J) = C(I,J) + A(I,K)*B(J,K)
				END DO
		END DO
	END DO
	END
