	REAL FUNCTION NORMA_INF(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL SOMMA
	NORMA_INF=0
	DO I=1,N
		SOMMA=0
		DO J=1,N
			SOMMA=SOMMA+ABS(A(I,J))
		END DO 
		IF(NORMA_INF.LE.SOMMA) NORMA_INF=SOMMA
	END DO 
	END 
