	REAL FUNCTION NORMA_1(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL SOMMA
	NORMA_1=0
      DO J=1,N
		SOMMA=0
          DO I=1,N
			SOMMA=SOMMA+ABS(A(I,J))
		END DO
		IF (NORMA_1.LT.SOMMA) NORMA_1=SOMMA
	END DO 
	END 