	REAL FUNCTION NORMA_1(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL SOMMA
	NORMA_1=0
	DO J=1,N
		SOMMA=0
  	DO I=1,N
			SOMMA=SOMMA+ABS(A(I,J))
		END DO
		IF(NORMA_1.LT.SOMMA)NORMA_1=SOMMA
	END DO
	END

	REAL FUNCTION NORMA_2(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL A2(N,N)
	COMPLEX EVAL(N)
	CALL MATRIX_MUL_T(A,A2,N_MAX,N,N)
	CALL EVLRG(N,A2,N,EVAL)
	NORMA_2=SQRT(ABS(EVAL(1)))
	END

	SUBROUTINE MATRIX_MUL_T(A,C,NMAX_A,NMAX_C,N)
	REAL A(NMAX_A,N),C(NMAX_C,N),SOMMA
	INTEGER I,J,K
	DO I=1,N
		DO J=1,N
			SOMMA=0
			DO K=1,N
				SOMMA=SOMMA+A(I,K)*A(J,K)
			END DO
			C(I,J)=SOMMA
		END DO
	END DO
	END

	REAL FUNCTION NORMA_INF(A,N_MAX,N)
	REAL A(N_MAX,N)
	REAL SOMMA
	NORMA_INF=0
	DO I=1,N
		SOMMA=0
		DO J=1,N
			SOMMA=SOMMA+ABS(A(I,J))
		END DO
		IF(NORMA_INF.LE.SOMMA) NORMA_INF=SOMMA
	END DO
	END


	REAL FUNCTION NORMA_FROBENIUS(A,N_MAX,N)
	REAL A(N_MAX,N)
	NORMA_FROBENIUS=0
	DO I=1,N
		DO J=1,N
			NORMA_FROBENIUS=NORMA_FROBENIUS+(A(I,J)*A(I,J))
		END DO
	END DO
	NORMA_FROBENIUS=SQRT(NORMA_FROBENIUS)
	END